#!/bin/bash -login

#SBATCH --time=04:00:00			      		### limit of wall clock time - how long the job will run (same as -t)
#SBATCH --ntasks=1				          	### number of tasks - how many tasks (nodes) that you require (same as -n)
#SBATCH --cpus-per-task=100		    		### number of CPUs (or cores) per task (same as -c)
#SBATCH --mem=32G			            		### memory required per node - amount of memory (in bytes)
#SBATCH --job-name constaxOomy				### you can give your job a name for easier identification (same as -J)
#SBATCH -A shade-cole-bonito

cd ${SLURM_SUBMIT_DIR}

conda activate py3

/mnt/home/rennickb/constax/CONSTAX_May2020/constax.sh \
--num_threads $SLURM_CPUS_PER_TASK \
--mem $SLURM_MEM_PER_NODE \
--db /mnt/research/bonito_lab/CONSTAX_May2020/UNITE_Fungi_tf/sh_general_release_eukaryotes_91074_RepS_04.02.2020.fasta \
--train \
--input /mnt/home/rennickb/20210402_Amplicon_PE300/clustered_OTU_ESV/otus_R1.fasta \
--isolates /mnt/home/rennickb/ZachsOomyceteReferenceFile/oomyceteCurratedData.fasta \
--isolates_query_coverage=97 \
--isolates_percent_identity=97 \
--high_level_db /mnt/ufs18/rs-022/bonito_lab/CONSTAX_May2020/sh_general_release_all_10.05.2021/sh_general_release_dynamic_all_10.05.2021.fasta \
--high_level_query_coverage=60 \
--high_level_percent_identity=60 \
--trainfile /mnt/home/rennickb/DATABASES/training_files_Oomy/ \
--tax /mnt/home/rennickb/CONSTAX_v2/taxonomy_assignments_Oomy22_zach/ \
--output /mnt/home/rennickb/CONSTAX_v2/taxonomy_assignments_Oomy22_zach/ \
--conf 0.8 \
--blast \
--make_plot \
--pathfile /mnt/home/rennickb/20210402_Amplicon_PE300/pathfile.txt \
--sintax_path /mnt/research/rdp/public/thirdParty/usearch10.0.240_i86linux64 \
--rdp_path /mnt/home/rennickb/anaconda3/pkgs/rdptools-2.0.3-hdfd78af_1/bin/classifier \
--constax_path /mnt/home/rennickb/anaconda3/envs/py3/opt/constax-2.0.17-0

conda deactivate
